sudo: required
dist: trusty
language: node_js
node_js:
  - stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


env:
  global:
  - ENCRYPTION_LABEL: "e281ba595e00"
  - COMMIT_AUTHOR_EMAIL: "adam@tokbox.com"
  - OT_API_KEY: "1052571"
  - OT_SESSION_ID: "2_MX4xMDUyNTcxfn4xNDg1OTE2OTk4MTgwfnJYV2QrZXJGaDhwWlBTVDdLdkptNmF2en5-"
  - INTEGRATION_CMD: "'npm run integration'"

  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=stable

before_script:
  - cd demo && ./travis-start-demo.sh

script:
  - npm test

after_success:
  - ./deploy.sh
